### PR TITLE
rlog

### PR DESCRIPTION
**Pull request by Driim**
I do not know is necessary or not, but I have added a rlog in the project. But in project files there are my path.

### CODE REVIEW

**Comment by jetwhiz** [comment]
Thanks, @Driim!  The code looks good, but I'll have to play around with it more this weekend to be sure any bugs are ironed out with the merge.  Do you know if this version has a similar issue as the encfs4win-reloaded implementation did -- https://github.com/kriswebdev/encfs4win-reloaded/issues/2?

**Comment by Driim** [comment]
No, this version doesn't have this issue. You can check my [commit ](https://github.com/Driim/WinEncFS/commit/85804e9b9d75cf8473e6389294b5c342703f61da)and his [bugfix ](https://github.com/kriswebdev/encfs4win-reloaded/commit/ccc8746e271426e1901a8d470029b0fc21258d12)

**Comment by jetwhiz** [comment]
Hi Driim 

Could you test this branch to make sure everything works OK on your end?  

https://github.com/jetwhiz/encfs4win/tree/Driim-pull6

It should include your pull request, in addition to modifications done for compatibility with encfs4win.

**Comment by jetwhiz** [comment]
I have finished the merge for the rlog code -- thanks for the pull contribution, Driim!

**Pull request closed without merging**
